import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const localesDir = path.resolve(__dirname, '../src/locales');
const outputFile = path.join(localesDir, 'index.ts');

const header = `// This file is auto-generated by scripts/generate-locales.ts
// It exports all available locales for easy importing.
// For example: import { ptBR } from 'dt-i18n/locales';\n\n`;

const localeFiles = fs.readdirSync(localesDir)
  .filter(file => file.endsWith('.ts') && file !== 'index.ts');

const exports = localeFiles.map(file => {
  const baseName = path.basename(file, '.ts');
  // Convert kebab-case (pt-br) to camelCase (ptBR) for a valid JS identifier
  const varName = baseName.replace(/-(\w)/g, (_, letter) => letter.toUpperCase());
  return `export { default as ${varName} } from './${baseName}';`;
}).join('\n');

fs.writeFileSync(outputFile, header + exports + '\n');

console.log('Successfully generated src/locales/index.ts');
